service: nodejs-assignment

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    APP_NAME: ${self:service}
    AWS_ACCESS_KEY_ID: id_key
    AWS_SECRET_ACCESS_KEY: access_key

package:
  exclude:
    - .env
    - coverage/**

plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

functions:
  create:
    handler: lib/handlers/offer/create.handler
    events:
      - http:
          path: /create/{amount}
          method: get
  # name: create
  #   handler: lib/handlers/offer/create.handler
  #   events:
  #     - http:
  #         path: /create/{amount}
  #         method: get
  # - '${file(lib/handlers/offer/serverless.yml)}'
  # - '${file(lib/handlers/disburse/serverless.yml)}'

# functions:
#   createOffer:
#     name: create
#     handler: lib/app1/handlers.create
#     events:
#       - http:
#           path: /create/{amount}
#           method: get

#   function2:
#     name: function2
#     handler: lib/app1/functions.function2
#     events:
#       - http:
#           path: /delete/{id}
#           method: get

#   function3:
#     name: function3
#     handler: lib/app1/functions.function3
#     events:
#       - http:
#           path: /all
#           method: get

#   function4:
#     name: function4
#     handler: lib/app1/functions.function4
#     events:
#       - http:
#           path: /disburse/{id}
#           method: get

# custom:
#   serverless-offline:
#     host: 0.0.0.0 # for docker container hosting
