service: nodejs-assignment

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    APP_NAME: ${self:service}
    AWS_ACCESS_KEY_ID: id_key
    AWS_SECRET_ACCESS_KEY: access_key
    AWS_ENDPOINT: aws_endpoint
    AWS_REGION: aws_region

package:
  exclude:
    - .env
    - coverage/**

plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

functions:
  create:
    handler: lib/handlers/offer/create.handler
    events:
      - http:
          path: /create/{companyId}/{amount}
          method: get
  delete:
    handler: lib/handlers/offer/delete.handler
    events:
      - http:
          path: /delete/{id}
          method: get
  list:
    handler: lib/handlers/offer/list.handler
    events:
      - http:
          path: /list
          method: get
